Models/ErrorViewModel.cs
using System;

namespace GetAGame.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GetAGame.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string OwnerName { get; set; }
        [Required]
        public string ImgURL { get; set; }
        [Required]
        public string Title { get; set; }
        public string Details { get; set; }
        [Required]
        public double Price { get; set; }
    }
}

Controllers/AddItemController.cs
using System.Threading.Tasks;
using GetAGame.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GetAGame.Controllers

{
    public class AddItemController : Controller
    {
        private readonly IitemsServices _itemsService;

        public AddItemController(IitemsServices itemsService)
        {
            _itemsService = itemsService;
        }
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddProcess([Bind("Title,ImgURL,Details,Price")] Models.Item item)
        {
            item.OwnerName = User.Identity.Name;
            await _itemsService.AddItemAsync(item);
            return Redirect("/Home");
        }
    }
}

Controllers/BuyItemController.cs
using System.Threading.Tasks;
using GetAGame.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GetAGame.Controllers
{
    public class BuyItemController : Controller
    {
        private readonly IitemsServices _itemsService;

        public BuyItemController(IitemsServices itemsService)
        {
            _itemsService = itemsService;
        }
        [Authorize]
        public async Task<IActionResult> Buy(int? id)
        {
            var item = await _itemsService.GetItemAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }
    }
}

Controllers/DeleteItemController.cs
using System.Threading.Tasks;
using GetAGame.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GetAGame.Controllers
{
    public class DeleteItemController : Controller
    {
        private readonly IitemsServices _itemsService;

        public DeleteItemController(IitemsServices itemsService)
        {
            _itemsService = itemsService;
        }
        [Authorize]

        public async Task<IActionResult> Delete(int id)
        {
            await _itemsService.DeleteItemByIdAsync(id);
            return Redirect("/Home");
        }
    }
}

Controllers/DetailsController.cs
using System.Threading.Tasks;
using GetAGame.Services;
using Microsoft.AspNetCore.Mvc;

namespace GetAGame.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IitemsServices _itemsService;

        public DetailsController(IitemsServices itemsService)
        {
            _itemsService = itemsService;
        }
        public async Task<IActionResult> Index(int? id)
        {
            var item = await _itemsService.GetItemAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GetAGame.Models;
using GetAGame.Services;
using Microsoft.AspNetCore.Authorization;

namespace GetAGame.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IitemsServices _itemsService;

        public HomeController(ILogger<HomeController> logger, IitemsServices itemsService)
        {
            _logger = logger;
            _itemsService = itemsService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _itemsService.GetItemsAsync());
        }

        public async Task<IActionResult> MyItems(string name)
        {
            var items = await _itemsService.GetItemsByNameAsync(name);
            return View(items);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AddItem/Add.cshtml
@model GetAGame.Models.Item
<h1>Add Item</h1>
<div class="card">

    <div class="card-body">
        <form asp-controller="AddItem" asp-action="AddProcess">
            <div class="form-group">
                <label asp-for="Title">Title</label>
                <input asp-for="Title" type="text" class="form-control" placeholder="Enter title" required>
            </div>
            <div class="form-group">
                <label asp-for="ImgURL">ImageURL</label>
                <input asp-for="ImgURL" type="url" class="form-control" placeholder="Enter url" required>
            </div>
            <div class="form-group">
                <label asp-for="Details" for="exampleFormControlTextarea1">Details</label>
                <textarea asp-for="Details" class="form-control" rows="3" required></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Price">Price</label>
                <input asp-for="Price" type="number" class="form-control" placeholder="Enter Price" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

Views/BuyItem/Buy.cshtml
@model GetAGame.Models.Item

@if (User.Identity.Name != Model.OwnerName)
{
    <div class="text-center">
        <div class="card">
            <img style="height:300px;width:300px;align-self:center;" src="@Model.ImgURL">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">
                    <ul class="list-group list-group-flush">
                        @{
                            var strings = @Model.Details.Split(".");
                            foreach (var item in strings)
                            {
                                <li class="list-group-item" style="text-align: left;">@item</li>
                            }
                        }
                        <li class="list-group-item" style="text-align: left;">-Price : @Model.Price$</li>
                    </ul>
                </p>
                <a href="#" class="btn btn-success">Confirm purchase</a>
                <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
}
else
{
    <h1>It is you item</h1>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back</a>
    <a asp-asp-controller="DeleteItem" asp-action="Delete" asp-rout-Id="@Model.Id" class="btn btn-danger">Delete Item</a>
}

Views/Details/Index.cshtml
@model GetAGame.Models.Item


<div class="text-center">
    <div class="card">
        <img src="@Model.ImgURL" style="height:300px;width:300px;align-self:center;">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">
                <ul class="list-group list-group-flush">
                    @{
                        var strings = @Model.Details.Split(".");
                        foreach (var item in strings)
                        {
                            <li class="list-group-item" style="text-align: left;">@item</li>
                        }
                    }

                </ul>

            </p>
            @if (User.Identity.Name != Model.OwnerName)
            {
                <a asp-controller="BuyItem" asp-action="Buy" class="btn btn-success" asp-route-Id="@Model.Id">Buy
                    @Model.Price$</a>
            }
                <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>

Views/Home/Index.cshtml
@model List<GetAGame.Models.Item>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<div class="text-center">
    <h1 class="display-4">Welcome To Your GamingStore!</h1>
    <p>Here you can find all the gaming related items available for you to buy</p>
    @if(!SignInManager.IsSignedIn(User))
    {
    <p>You can also <a  asp-area="Identity" asp-page="/Account/Register">register</a> to sell your items.</p>
    }
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">

                    <br />
                    <div class="card" style="width: auto; height:37rem;">
                        <br>
                        <img class="img-fluid" src="@item.ImgURL" , style="height:200px;width:200px;align-self:center;">
                        <div class="card-body">
                            <h5 class="card-title">@item.Title</h5>

                            <p class="card-text">@(string.Join(" ",item.Details.Split(" ").Take(10))+ "...")</p>

                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    More
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-controller="Details" asp-action="Index"
                                        asp-route-Id="@item.Id">More Details</a>
                                    @if (User.Identity.Name != item.OwnerName)
                                    {
                                        <a class="dropdown-item" asp-controller="BuyItem" asp-action="Buy"
                                            asp-route-Id="@item.Id">Buy @item.Price$</a>
                                    }
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
            }
        </div>
    </div>

Views/Home/MyItems.cshtml
@model List<GetAGame.Models.Item>

@if (Model.Count == 0)
{
    <h1>
        Hi @User.Identity.Name,you don't have any items.
    </h1>
    <a class="btn btn-primary" type="button" asp-action="Add" asp-controller="AddItem">
        Add new item
    </a>
}
else
{
    <h1 class="display-4">Your Items : </h1>
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 ">

                    <br />
                    <div class="card" style="width: auto;height:40rem;">
                        <br>
                        <img class="img-fluid" src="@item.ImgURL" , style="height:200px;width:200px;align-self:center;">
                        <div class="card-body">
                            <h5 class="card-title">@item.Title</h5>

                            <p class="card-text">@(string.Join(" ",item.Details.Split(" ").Take(10))+ "...")</p>

                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    More
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-controller="Details" asp-action="Index"
                                        asp-route-Id="@item.Id">More Details</a>

                                    <a class="dropdown-item" asp-controller="DeleteItem" asp-action="Delete"
                                        asp-route-Id="@item.Id">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GamingStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">GamingStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="MyItems"
    asp-route-name="@User.Identity.Name">My
                                    Items</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="AddItem" asp-action="Add"
asp-route-name="@User.Identity.Name">Add
                                Item</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GetAGame
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>